on: 
    pull_request:
        branches:
            - test1

jobs:
  onelifedata7_pr_summary:
    runs-on: ubuntu-latest
    steps:


      - id: setup-python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
            

      - name: Checkout Merged PR
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'


      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
            separator: "\n"
            old_new_files_separator: "\n"
            output_renamed_files_as_deleted_and_added: true
            include_all_old_new_renamed_files: true
            recover_deleted_files: true

            
      - id: readable_assets
        run: python readableAssets.py
        shell: bash
        env:
            REPO: ${{ github.repository }}
            REPO_PATH: ${{ github.workspace }}
            PRNUM: ${{ github.event.number }}
            CHANGES_ALL: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
            CHANGES_DELETED: ${{ steps.changed-files.outputs.deleted_files }}
            CHANGES_ADDED: ${{ steps.changed-files.outputs.added_files }}
            CHANGES_RENAME_PAIRS: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}
            
            VAR1: ${{ github.head_ref }}
            VAR2: ${{ github.base_ref }}


      - id: comment_pr
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
            message: |
                ${{ steps.readable_assets.outputs.OUTPUT_CHANGES }}