on: 
    pull_request:
        branches:
            - test1

jobs:
  onelifedata7_pr_summary:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
    
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
            prNumber: ${{ github.event.number }}
            fileOutput: 'json'
            
      - id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - id: readable_assets
        run: python readableAssets.py
        shell: bash
        env:
            INPUT_CHANGES: ${{ steps.file_changes.outputs.files }}
        
      - id: comment_pr
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
            message: |
              Hello world ! ${{ steps.readable_assets.outputs.OUTPUT_CHANGES }}
