on: 
    pull_request:
        branches:
            - test1

jobs:
  onelifedata7_pr_summary:
    runs-on: ubuntu-latest
    steps:


      - name: Checkout Main
        uses: actions/checkout@v3
        with:
            ref: 'test1'
          
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
            prNumber: ${{ github.event.number }}
            fileOutput: 'json'
            
      - id: setup-python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
          
      - id: readable_assets
        run: python readableAssets.py
        shell: bash
        env:
            REPO_PATH: ${{ github.workspace }}
            INPUT_CHANGES: ${{ steps.file_changes.outputs.files_removed }}
            HEAD_REF: ${{ github.head_ref }}
            BASE_REF: ${{ github.base_ref }}
        
      - id: comment_pr
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
            message: |
              ${{ steps.readable_assets.outputs.OUTPUT_CHANGES }}
