on: 
    pull_request:
        branches:
            - test1

jobs:
  onelifedata7_pr_summary:
    runs-on: ubuntu-latest
    steps:


      - id: setup-python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
            

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
            prNumber: ${{ github.event.number }}
            fileOutput: 'json'

            
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'


      - id: comment_pr
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
            message: |
                ## Files
                ${{ steps.file_changes.outputs.files}}
                ## Files Modified
                ${{ steps.file_changes.outputs.files_modified}}
                ## Files Added
                ${{ steps.file_changes.outputs.files_added}}
                ## Files Removed
                ${{ steps.file_changes.outputs.files_removed}}
