on: 
    pull_request:
        branches:
            - test1

jobs:
  onelifedata7_pr_summary:
    runs-on: ubuntu-latest
    steps:


      - id: setup-python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
            

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
            include_all_old_new_renamed_files: "true"

            



      - id: comment_pr
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
            message: |
                ## Files Changed
                ${{ steps.changed-files.outputs.all_changed_files }}
                ## Changed and Modified Files
                ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
                ## Files Added
                ${{ steps.changed-files.outputs.all_modified_files }}
                ## Files Removed
                ${{ steps.changed-files.outputs.deleted_files }}
                ## Files Renamed 
                ${{ steps.changed-files.outputs.all_old_new_renamed_files }}
