on: 
    pull_request

jobs:
  onelifedata7_pr_summary:
    runs-on: ubuntu-latest
    steps:


      - id: setup-python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
            

      - id: checkout
        name: Checkout Merged PR
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'


      - id: changed-files
        name: Get changed files
        uses: tj-actions/changed-files@v43
        with:
            separator: "\n"
            old_new_files_separator: "\n"
            output_renamed_files_as_deleted_and_added: true
            include_all_old_new_renamed_files: true
            recover_deleted_files: true
            # recover_deleted_files_to_destination: "deleted_files"
            
      - id: readable-assets
        name: Parse asset changes to be more readable
        run: python readableAssets.py
        shell: bash
        env:
            REPO: ${{ github.repository }}
            REPO_PATH: ${{ github.workspace }}
            PRNUM: ${{ github.event.number }}
            CHANGES_ALL: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
            CHANGES_DELETED: ${{ steps.changed-files.outputs.deleted_files }}
            CHANGES_ADDED: ${{ steps.changed-files.outputs.added_files }}
            CHANGES_RENAME_PAIRS: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}


      - id: comment-pull-request
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
            message: |
                ${{ steps.readable-assets.outputs.OUTPUT_MESSAGE }}