name: Renumber objects and sprites

on: 
  pull_request_review:
    branches:
      - scripts_test
    types: 
      - submitted
    

jobs:
  renumber:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    
      - run: |
              echo "${{ github.head_ref }}"
              echo "${{ github.base_ref }}"
              echo "${{ github.ref }}"
              echo "${{ github.event.pull_request.number }}"
              echo "${{ github.event.pull_request.head.ref }}"
              echo "..."
              echo "${{ toJson(github) }}"
    
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          fetch-depth: '0'

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Object IDs calculation
        id: object_id_calculation
        run: |
              nextID=$( cat objects/nextObjectNumber.txt )
              maxID=$(ls -v objects/[0-9]* | tail -1 | sed 's/objects\///' | sed 's/.txt//')
              echo "${{ github.head_ref }}"
              echo "${{ github.base_ref }}"
              echo "${{ github.ref }}"
              echo $nextID
              echo $maxID
              echo "nextID=$nextID" >> "$GITHUB_OUTPUT"
              echo "maxID=$maxID" >> "$GITHUB_OUTPUT"
              
      - run: |
              echo "BRUH"
              echo "${{ steps.object_id_calculation.outputs.maxID }}"
              echo "${{ steps.object_id_calculation.outputs.nextID }}"
              echo "${{ github.head_ref }}"
              echo "${{ github.base_ref }}"

      - if: steps.object_id_calculation.outputs.maxID > steps.object_id_calculation.outputs.nextID
        name: Renumbering objects
        run: |
              echo "HERE"
              nextID=$( cat objects/nextObjectNumber.txt )
              maxID=$(ls -v objects/[0-9]* | tail -1 | sed 's/objects\///' | sed 's/.txt//')
              start_number=$maxID
              for fn in objects/[0-9]*.txt; do
                  id="${fn//[^0-9]/}"
                  (( id > nextID && id < start_number )) && start_number=$id
              done
              node RenumberObjects.js $start_number
              maxID=$(ls -v objects/[0-9]* | tail -1 | sed 's/objects\///' | sed 's/.txt//')
              echo -n $((maxID + 1)) > objects/nextObjectNumber.txt

      - if: steps.object_id_calculation.outputs.maxID > steps.object_id_calculation.outputs.nextID
        uses: EndBug/add-and-commit@v9
        with:
          message: "Renumber objects"
          default_author: github_actions
        